package EpamLearn.core;

public enum Subjects {
  HISTORY,
  CULTURAL_STUDIES,
  PHILOSOPHY,
  LOGICS,
  ETHICS,
  SOCIOLOGY,
  ECONOMY,
  JURISPRUDENCE,
  HIGHER_MATHEMATICS,
  NATURAL_SCIENCE,
  FOREIGN_LANGUAGE,
  PHYSICAL_CULTURE,
  THERMODYNAMICS,
  METROLOGY,
  HYDROGASDYNAMICS,
  DRAWING
}
